Update command line flags for pgsql plotting scripts

diff --git a/bin/pgsql/dbt-pgsql-plot-database-stats b/bin/pgsql/dbt-pgsql-plot-database-stats
--- a/bin/pgsql/dbt-pgsql-plot-database-stats
+++ b/bin/pgsql/dbt-pgsql-plot-database-stats
@@ -7,17 +7,58 @@
 # Copyright (C) 2014      2ndQuadrant, Ltd.
 #
 
-CSVFILE=$1
-OUTPUTDIR=$2
+usage()
+{
+	echo "`basename $0` is the PostgreSQL database statistics chart generator"
+	echo ""
+	echo "Usage:"
+	echo "  `basename $0` [OPTION]"
+	echo ""
+	echo "Options:"
+	echo "  -i CSV      path to CSV file"
+	echo "  -n DBNAME   database name"
+	echo "  -o PATH     output directory"
+}
 
-mkdir -p ${OUTPUTDIR}
-if [ ! -d "${OUTPUTDIR}" ]; then
-	echo "Failed to create directory ${OUTPUTDIR}"
+while getopts "hi:n:o:" opt; do
+	case $opt in
+	h)
+		usage
+		exit 1
+		;;
+	i)
+		CSVFILE=$OPTARG
+		;;
+	n)
+		PGDATABASE=$OPTARG
+		;;
+	o)
+		OUTDIR=$OPTARG
+		mkdir -p $OUTDIR
+		if [ ! -d "$OUTDIR" ]; then
+			echo "ERROR: Failed to create directory $OUTDIR"
+			exit 1
+		fi
+		;;
+	\?)
+		usage
+		exit 1
+		;;
+	esac
+done
+
+if [ "x$CSVFILE" = "x" ]; then
+	error "ERROR: input CSV file was not specified with -i"
+	exit 1
+fi
+
+if [ "x$OUTDIR" = "x" ]; then
+	error "ERROR: output directory was not specified with -o"
 	exit 1
 fi
 
 if [ "x$PGDATABASE" = "x" ]; then
-	echo "ERROR: PGDATABASE env variable not set"
+	echo "ERROR: PGDATABASE not set, use -n"
 	exit 1
 fi
 
@@ -56,7 +97,7 @@ df\$tup_updated <- df\$tup_updated - tmp
 tmp <- c(NA, df\$tup_deleted[-nrow(df)])
 df\$tup_deleted <- df\$tup_deleted - tmp
 
-bitmap("$OUTPUTDIR/db-stat-$PGDATABASE-connections.png",
+bitmap("$OUTDIR/db-stat-$PGDATABASE-connections.png",
        type="png16m", units="px", width=1280, height=800, res=150, taa=4,
        gaa=4)
 plot(df\$ctime, df\$numbackends,  xlim=c(0, max(df\$ctime)),
@@ -69,7 +110,7 @@ invisible(dev.off())
 color <- rainbow(2)
 pch <- c(1, 2)
 
-bitmap("$OUTPUTDIR/db-stat-$PGDATABASE-xacts.png",
+bitmap("$OUTDIR/db-stat-$PGDATABASE-xacts.png",
        type="png16m", units="px", width=1280, height=800, res=150, taa=4,
        gaa=4)
 plot(df\$ctime, df\$xact_commit,  xlim=c(0, max(df\$ctime)),
@@ -82,7 +123,7 @@ legend('topright', c("Commits", "Rollbacks"), pch = pch, col=color)
 grid(col="gray")
 invisible(dev.off())
 
-bitmap("$OUTPUTDIR/db-stat-$PGDATABASE-blocks.png",
+bitmap("$OUTDIR/db-stat-$PGDATABASE-blocks.png",
        type="png16m", units="px", width=1280, height=800, res=150, taa=4,
        gaa=4)
 plot(df\$ctime, df\$blks_read,  xlim=c(0, max(df\$ctime)),
diff --git a/bin/pgsql/dbt-pgsql-plot-index-stats b/bin/pgsql/dbt-pgsql-plot-index-stats
--- a/bin/pgsql/dbt-pgsql-plot-index-stats
+++ b/bin/pgsql/dbt-pgsql-plot-index-stats
@@ -3,17 +3,62 @@
 # This file is released under the terms of the Artistic License.
 # Please see the file LICENSE, included in this package, for details.
 #
-# Copyright (C) 2010-2014 Mark Wong
-#               2014      2ndQuadrant, Ltd.
+# Copyright (C) 2014      2ndQuadrant, Ltd.
+#               2010-2022 Mark Wong
 #
 
-CSVFILE=$1
-INDEXNAME=$2
-OUTPUTDIR=$3
+usage()
+{
+	echo "`basename $0` is the PostgreSQL index statistics chart generator"
+	echo ""
+	echo "Usage:"
+	echo "  `basename $0` [OPTION]"
+	echo ""
+	echo "Options:"
+	echo "  -i CSV      path to CSV file"
+	echo "  -n INDEX    index name"
+	echo "  -o PATH     output directory"
+}
 
-mkdir -p ${OUTPUTDIR}
-if [ ! -d "${OUTPUTDIR}" ]; then
-	echo "Failed to create directory ${OUTPUTDIR}"
+while getopts "hi:n:o:" opt; do
+	case $opt in
+	h)
+		usage
+		exit 1
+		;;
+	i)
+		CSVFILE=$OPTARG
+		;;
+	n)
+		INDEXNAME=$OPTARG
+		;;
+	o)
+		OUTDIR=$OPTARG
+		mkdir -p $OUTDIR
+		if [ ! -d "$OUTDIR" ]; then
+			echo "ERROR: Failed to create directory $OUTDIR"
+			exit 1
+		fi
+		;;
+	\?)
+		usage
+		exit 1
+		;;
+	esac
+done
+
+if [ "x$CSVFILE" = "x" ]; then
+	error "ERROR: input CSV file was not specified with -i"
+	exit 1
+fi
+
+if [ "x$OUTDIR" = "x" ]; then
+	error "ERROR: output directory was not specified with -o"
+	exit 1
+fi
+
+if [ "x$INDEXNAME" = "x" ]; then
+	echo "ERROR: index name not set, use -n"
 	exit 1
 fi
 
@@ -40,7 +85,7 @@ df\$idx_blks_read <- df\$idx_blks_read - tmp
 tmp <- c(NA, df\$idx_blks_hit[-nrow(df)])
 df\$idx_blks_hit <- df\$idx_blks_hit - tmp
 
-bitmap("${OUTPUTDIR}/index-stat-${INDEXNAME}-idx_scan.png",
+bitmap("${OUTDIR}/index-stat-${INDEXNAME}-idx_scan.png",
        type="png16m", units="px", width=1280, height=800, res=150, taa=4,
        gaa=4)
 plot(df\$ctime, df\$idx_scan, xlim=c(0, max(df\$ctime)),
@@ -50,7 +95,7 @@ plot(df\$ctime, df\$idx_scan, xlim=c(0, max(df\$ctime)),
 grid(col="gray")
 invisible(dev.off())
 
-bitmap("${OUTPUTDIR}/index-stat-${INDEXNAME}-idx_tup_read.png",
+bitmap("${OUTDIR}/index-stat-${INDEXNAME}-idx_tup_read.png",
        type="png16m", units="px", width=1280, height=800, res=150, taa=4,
        gaa=4)
 plot(df\$ctime, df\$idx_tup_read, xlim=c(0, max(df\$ctime)),
@@ -60,7 +105,7 @@ plot(df\$ctime, df\$idx_tup_read, xlim=c(0, max(df\$ctime)),
 grid(col="gray")
 invisible(dev.off())
 
-bitmap("${OUTPUTDIR}/index-stat-${INDEXNAME}-idx_tup_fetch.png",
+bitmap("${OUTDIR}/index-stat-${INDEXNAME}-idx_tup_fetch.png",
        type="png16m", units="px", width=1280, height=800, res=150, taa=4,
        gaa=4)
 plot(df\$ctime, df\$idx_tup_fetch, xlim=c(0, max(df\$ctime)),
@@ -70,7 +115,7 @@ plot(df\$ctime, df\$idx_tup_fetch, xlim=c(0, max(df\$ctime)),
 grid(col="gray")
 invisible(dev.off())
 
-bitmap("${OUTPUTDIR}/index-stat-${INDEXNAME}-idx_blks_read.png",
+bitmap("${OUTDIR}/index-stat-${INDEXNAME}-idx_blks_read.png",
        type="png16m", units="px", width=1280, height=800, res=150, taa=4,
        gaa=4)
 plot(df\$ctime, df\$idx_blks_read, xlim=c(0, max(df\$ctime)),
@@ -80,7 +125,7 @@ plot(df\$ctime, df\$idx_blks_read, xlim=c(0, max(df\$ctime)),
 grid(col="gray")
 invisible(dev.off())
 
-bitmap("${OUTPUTDIR}/index-stat-${INDEXNAME}-idx_blks_hit.png",
+bitmap("${OUTDIR}/index-stat-${INDEXNAME}-idx_blks_hit.png",
        type="png16m", units="px", width=1280, height=800, res=150, taa=4,
        gaa=4)
 plot(df\$ctime, df\$idx_blks_hit, xlim=c(0, max(df\$ctime)),
@@ -95,7 +140,7 @@ invisible(dev.off())
 color <- rainbow(2)
 pch <- c(1, 2)
 
-bitmap("${OUTPUTDIR}/index-stat-${INDEXNAME}-idx_blks.png",
+bitmap("${OUTDIR}/index-stat-${INDEXNAME}-idx_blks.png",
        type="png16m", units="px", width=1280, height=800, res=150, taa=4,
        gaa=4)
 plot(df\$ctime, df\$idx_blks_read, xlim=c(0, max(df\$ctime)),
diff --git a/bin/pgsql/dbt-pgsql-plot-table-stats b/bin/pgsql/dbt-pgsql-plot-table-stats
--- a/bin/pgsql/dbt-pgsql-plot-table-stats
+++ b/bin/pgsql/dbt-pgsql-plot-table-stats
@@ -3,18 +3,65 @@
 # This file is released under the terms of the Artistic License.
 # Please see the file LICENSE, included in this package, for details.
 #
-# Copyright (C) 2010-2014 Mark Wong
-#               2014      2ndQuadrant, Ltd.
+# Copyright (C) 2014      2ndQuadrant, Ltd.
+#               2010-2022 Mark Wong
 #
 
-CSVFILE=$1
-TABLENAME=$2
-OUTPUTDIR=$3
+usage()
+{
+	echo "`basename $0` is the PostgreSQL table statistics chart generator"
+	echo ""
+	echo "Usage:"
+	echo "  `basename $0` [OPTION]"
+	echo ""
+	echo "Options:"
+	echo "  -i CSV      path to CSV file"
+	echo "  -n TABLE    table name"
+	echo "  -o PATH     output directory"
+}
 
-mkdir -p ${OUTPUTDIR}
-if [ ! -d "${OUTPUTDIR}" ]; then
-	echo "Failed to create directory ${OUTPUTDIR}"
+error() {
+	echo "ERROR: $@"
 	exit 1
+}
+
+while getopts "hi:n:o:" opt; do
+	case $opt in
+	h)
+		usage
+		exit 1
+		;;
+	i)
+		CSVFILE=$OPTARG
+		;;
+	n)
+		TABLENAME=$OPTARG
+		;;
+	o)
+		OUTDIR=$OPTARG
+		mkdir -p $OUTDIR
+		if [ ! -d "$OUTDIR" ]; then
+			echo "ERROR: Failed to create directory $OUTDIR"
+			exit 1
+		fi
+		;;
+	\?)
+		usage
+		exit 1
+		;;
+	esac
+done
+
+if [ "x$CSVFILE" = "x" ]; then
+	error "input CSV file was not specified with -i"
+fi
+
+if [ "x$OUTDIR" = "x" ]; then
+	error "output directory was not specified with -o"
+fi
+
+if [ "x$TABLENAME" = "x" ]; then
+	error "table name not set, use -n"
 fi
 
 R --slave --no-save << __EOF__
@@ -79,7 +126,7 @@ df\$tidx_blks_read <- df\$tidx_blks_read - tmp
 tmp <- c(NA, df\$tidx_blks_hit[-nrow(df)])
 df\$tidx_blks_hit <- df\$tidx_blks_hit - tmp
 
-bitmap("${OUTPUTDIR}/table-stat-${TABLENAME}-seq_scan.png",
+bitmap("${OUTDIR}/table-stat-${TABLENAME}-seq_scan.png",
        type="png16m", units="px", width=1280, height=800, res=150, taa=4,
        gaa=4)
 plot(df\$ctime, df\$seq_scan, xlim=c(0, max(df\$ctime)),
@@ -89,7 +136,7 @@ plot(df\$ctime, df\$seq_scan, xlim=c(0, max(df\$ctime)),
 grid(col="gray")
 invisible(dev.off())
 
-bitmap("${OUTPUTDIR}/table-stat-${TABLENAME}-seq_tup_read.png",
+bitmap("${OUTDIR}/table-stat-${TABLENAME}-seq_tup_read.png",
        type="png16m", units="px", width=1280, height=800, res=150, taa=4,
        gaa=4)
 plot(df\$ctime, df\$seq_tup_read, xlim=c(0, max(df\$ctime)),
@@ -99,7 +146,7 @@ plot(df\$ctime, df\$seq_tup_read, xlim=c(0, max(df\$ctime)),
 grid(col="gray")
 invisible(dev.off())
 
-bitmap("${OUTPUTDIR}/table-stat-${TABLENAME}-idx_scan.png",
+bitmap("${OUTDIR}/table-stat-${TABLENAME}-idx_scan.png",
        type="png16m", units="px", width=1280, height=800, res=150, taa=4,
        gaa=4)
 plot(df\$ctime, df\$idx_scan, xlim=c(0, max(df\$ctime)),
@@ -109,7 +156,7 @@ plot(df\$ctime, df\$idx_scan, xlim=c(0, max(df\$ctime)),
 grid(col="gray")
 invisible(dev.off())
 
-bitmap("${OUTPUTDIR}/table-stat-${TABLENAME}-idx_tup_fetch.png",
+bitmap("${OUTDIR}/table-stat-${TABLENAME}-idx_tup_fetch.png",
        type="png16m", units="px", width=1280, height=800, res=150, taa=4,
        gaa=4)
 plot(df\$ctime, df\$idx_tup_fetch, xlim=c(0, max(df\$ctime)),
@@ -119,7 +166,7 @@ plot(df\$ctime, df\$idx_tup_fetch, xlim=c(0, max(df\$ctime)),
 grid(col="gray")
 invisible(dev.off())
 
-bitmap("${OUTPUTDIR}/table-stat-${TABLENAME}-n_tup_ins.png",
+bitmap("${OUTDIR}/table-stat-${TABLENAME}-n_tup_ins.png",
        type="png16m", units="px", width=1280, height=800, res=150, taa=4,
        gaa=4)
 plot(df\$ctime, df\$n_tup_ins, xlim=c(0, max(df\$ctime)),
@@ -129,7 +176,7 @@ plot(df\$ctime, df\$n_tup_ins, xlim=c(0, max(df\$ctime)),
 grid(col="gray")
 invisible(dev.off())
 
-bitmap("${OUTPUTDIR}/table-stat-${TABLENAME}-n_tup_upd.png",
+bitmap("${OUTDIR}/table-stat-${TABLENAME}-n_tup_upd.png",
        type="png16m", units="px", width=1280, height=800, res=150, taa=4,
        gaa=4)
 plot(df\$ctime, df\$n_tup_upd, xlim=c(0, max(df\$ctime)),
@@ -139,7 +186,7 @@ plot(df\$ctime, df\$n_tup_upd, xlim=c(0, max(df\$ctime)),
 grid(col="gray")
 invisible(dev.off())
 
-bitmap("${OUTPUTDIR}/table-stat-${TABLENAME}-n_tup_del.png",
+bitmap("${OUTDIR}/table-stat-${TABLENAME}-n_tup_del.png",
        type="png16m", units="px", width=1280, height=800, res=150, taa=4,
        gaa=4)
 plot(df\$ctime, df\$n_tup_del, xlim=c(0, max(df\$ctime)),
@@ -149,7 +196,7 @@ plot(df\$ctime, df\$n_tup_del, xlim=c(0, max(df\$ctime)),
 grid(col="gray")
 invisible(dev.off())
 
-bitmap("${OUTPUTDIR}/table-stat-${TABLENAME}-n_tup_hot_upd.png",
+bitmap("${OUTDIR}/table-stat-${TABLENAME}-n_tup_hot_upd.png",
        type="png16m", units="px", width=1280, height=800, res=150, taa=4,
        gaa=4)
 plot(df\$ctime, df\$n_tup_hot_upd, xlim=c(0, max(df\$ctime)),
@@ -159,7 +206,7 @@ plot(df\$ctime, df\$n_tup_hot_upd, xlim=c(0, max(df\$ctime)),
 grid(col="gray")
 invisible(dev.off())
 
-bitmap("${OUTPUTDIR}/table-stat-${TABLENAME}-n_live_tup.png",
+bitmap("${OUTDIR}/table-stat-${TABLENAME}-n_live_tup.png",
        type="png16m", units="px", width=1280, height=800, res=150, taa=4,
        gaa=4)
 plot(df\$ctime, df\$n_live_tup, xlim=c(0, max(df\$ctime)),
@@ -169,7 +216,7 @@ plot(df\$ctime, df\$n_live_tup, xlim=c(0, max(df\$ctime)),
 grid(col="gray")
 invisible(dev.off())
 
-bitmap("${OUTPUTDIR}/table-stat-${TABLENAME}-n_dead_tup.png",
+bitmap("${OUTDIR}/table-stat-${TABLENAME}-n_dead_tup.png",
        type="png16m", units="px", width=1280, height=800, res=150, taa=4,
        gaa=4)
 plot(df\$ctime, df\$n_dead_tup, xlim=c(0, max(df\$ctime)),
@@ -179,7 +226,7 @@ plot(df\$ctime, df\$n_dead_tup, xlim=c(0, max(df\$ctime)),
 grid(col="gray")
 invisible(dev.off())
 
-bitmap("${OUTPUTDIR}/table-stat-${TABLENAME}-heap_blks_read.png",
+bitmap("${OUTDIR}/table-stat-${TABLENAME}-heap_blks_read.png",
        type="png16m", units="px", width=1280, height=800, res=150, taa=4,
        gaa=4)
 plot(df\$ctime, df\$heap_blks_read, xlim=c(0, max(df\$ctime)),
@@ -189,7 +236,7 @@ plot(df\$ctime, df\$heap_blks_read, xlim=c(0, max(df\$ctime)),
 grid(col="gray")
 invisible(dev.off())
 
-bitmap("${OUTPUTDIR}/table-stat-${TABLENAME}-heap_blks_hit.png",
+bitmap("${OUTDIR}/table-stat-${TABLENAME}-heap_blks_hit.png",
        type="png16m", units="px", width=1280, height=800, res=150, taa=4,
        gaa=4)
 plot(df\$ctime, df\$heap_blks_hit, xlim=c(0, max(df\$ctime)),
@@ -199,7 +246,7 @@ plot(df\$ctime, df\$heap_blks_hit, xlim=c(0, max(df\$ctime)),
 grid(col="gray")
 invisible(dev.off())
 
-bitmap("${OUTPUTDIR}/table-stat-${TABLENAME}-idx_blks_read.png",
+bitmap("${OUTDIR}/table-stat-${TABLENAME}-idx_blks_read.png",
        type="png16m", units="px", width=1280, height=800, res=150, taa=4,
        gaa=4)
 plot(df\$ctime, df\$idx_blks_read, xlim=c(0, max(df\$ctime)),
@@ -209,7 +256,7 @@ plot(df\$ctime, df\$idx_blks_read, xlim=c(0, max(df\$ctime)),
 grid(col="gray")
 invisible(dev.off())
 
-bitmap("${OUTPUTDIR}/table-stat-${TABLENAME}-idx_blks_hit.png",
+bitmap("${OUTDIR}/table-stat-${TABLENAME}-idx_blks_hit.png",
        type="png16m", units="px", width=1280, height=800, res=150, taa=4,
        gaa=4)
 plot(df\$ctime, df\$idx_blks_hit, xlim=c(0, max(df\$ctime)),
@@ -219,7 +266,7 @@ plot(df\$ctime, df\$idx_blks_hit, xlim=c(0, max(df\$ctime)),
 grid(col="gray")
 invisible(dev.off())
 
-bitmap("${OUTPUTDIR}/table-stat-${TABLENAME}-toast_blks_read.png",
+bitmap("${OUTDIR}/table-stat-${TABLENAME}-toast_blks_read.png",
        type="png16m", units="px", width=1280, height=800, res=150, taa=4,
        gaa=4)
 plot(df\$ctime, df\$toast_blks_read, xlim=c(0, max(df\$ctime)),
@@ -229,7 +276,7 @@ plot(df\$ctime, df\$toast_blks_read, xlim=c(0, max(df\$ctime)),
 grid(col="gray")
 invisible(dev.off())
 
-bitmap("${OUTPUTDIR}/table-stat-${TABLENAME}-toast_blks_hit.png",
+bitmap("${OUTDIR}/table-stat-${TABLENAME}-toast_blks_hit.png",
        type="png16m", units="px", width=1280, height=800, res=150, taa=4,
        gaa=4)
 plot(df\$ctime, df\$toast_blks_hit, xlim=c(0, max(df\$ctime)),
@@ -239,7 +286,7 @@ plot(df\$ctime, df\$toast_blks_hit, xlim=c(0, max(df\$ctime)),
 grid(col="gray")
 invisible(dev.off())
 
-bitmap("${OUTPUTDIR}/table-stat-${TABLENAME}-tidx_blks_read.png",
+bitmap("${OUTDIR}/table-stat-${TABLENAME}-tidx_blks_read.png",
        type="png16m", units="px", width=1280, height=800, res=150, taa=4,
        gaa=4)
 plot(df\$ctime, df\$tidx_read, xlim=c(0, max(df\$ctime)),
@@ -249,7 +296,7 @@ plot(df\$ctime, df\$tidx_read, xlim=c(0, max(df\$ctime)),
 grid(col="gray")
 invisible(dev.off())
 
-bitmap("${OUTPUTDIR}/table-stat-${TABLENAME}-tidx_blks_hit.png",
+bitmap("${OUTDIR}/table-stat-${TABLENAME}-tidx_blks_hit.png",
        type="png16m", units="px", width=1280, height=800, res=150, taa=4,
        gaa=4)
 plot(df\$ctime, df\$tidx_blks_hit, xlim=c(0, max(df\$ctime)),
@@ -264,7 +311,7 @@ invisible(dev.off())
 color = rainbow(2)
 pch <- c(1, 2)
 
-bitmap("${OUTPUTDIR}/table-stat-${TABLENAME}-scans.png",
+bitmap("${OUTDIR}/table-stat-${TABLENAME}-scans.png",
        type="png16m", units="px", width=1280, height=800, res=150, taa=4,
        gaa=4)
 plot(df\$ctime, df\$seq_scan, xlim=c(0, max(df\$ctime)),
@@ -280,7 +327,7 @@ invisible(dev.off())
 color = rainbow(6)
 pch <- c(1, 6)
 
-bitmap("${OUTPUTDIR}/table-stat-${TABLENAME}-tup.png",
+bitmap("${OUTDIR}/table-stat-${TABLENAME}-tup.png",
        type="png16m", units="px", width=1280, height=800, res=150, taa=4,
        gaa=4)
 plot(df\$ctime, df\$seq_tup_read, xlim=c(0, max(df\$ctime)),
